apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: x7xz4x4co-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:221adedd4b4646093246beb17417bafa3c2d34f5@sha256:602b7f93175c8299452bdd082ea5c1e1498745c4ce9efe8b3351c3c05c96acce
          name: container-image
